# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: CI
on:
  push:
    branches: [staging, trying]
  pull_request: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  ci:
    name: CI
    # Ubuntu 22.04 does not support actions/setup-python with Python 3.6 as of
    # 2022-11-24. See https://github.com/actions/setup-python/issues/544.
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # Some Ferrocene builders require the use of Python 3.9. Use that on CI
      # to make sure there are no surprises when we import into Ferrocene.
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9.x"

      - name: Build documentation and check links
        run: ./make.py --check-links

      - name: Install Python dependencies
        run: python3 -m pip install reuse black flake8

      - name: Verify licensing metadata
        run: reuse lint

      - name: Verify Python code formatting
        run: black . --check --diff --color

      - name: Lint Python code with flake8
        run: flake8 . --exclude .venv
